### PR TITLE
fix(doxygen_cwd): Interpret paths relative to working dir

### PR DESCRIPTION
**Pull request by Maetveis**
Paths in the doxyfile are now interpreted relative to the doxygen working directory.

### CODE REVIEW

**Review by mb-emag — APPROVED** [review]
Thanks for fixing and contributing! 😃

**Review by twodrops — APPROVED** [review]
Thanks for the fix!
Sorry for the delay in approving. We have taken some steps so that this does not happen again.

**Comment by mb-emag** [comment]
Ah sorry I didn't noticed the failing pipeline when approving 😅 - The tests are failing. @Maetveis can you please have a look?

**Comment by Maetveis** [comment]
> Ah sorry I didn't noticed the failing pipeline when approving sweat_smile - The tests are failing. @Maetveis can you please have a look?

Yep, I needed to pass the param it in the tests also. I didn't add a testcase for this, as I'm not sure how to do it best, AFAICT pytest doesn't have optional parameters, and I didn't want to duplicate the testcase.

**Comment by mb-emag** [comment]
Thanks! I guess it would be quite hard to test that / mock it. Looks good for me 👍

**Pull request merged**
