### PR TITLE
81 support incremental behaviour for doxysphinx

### PR DESCRIPTION
**Pull request by aniketsalve22**
* Using HTML hash to compare the changes for achieving incremental behavior (Issue #81)

### CODE REVIEW

**Review by mb-emag — APPROVED** [review]
nice! 👍

**Review by twodrops — CHANGES_REQUESTED** [review]
As discussed, the current implementation is compressing all whitespaces, also the needed ones.

We need to retain the whitespaces within the HTML CDATA as we discussed [here](https://github.com/boschglobal/doxysphinx/issues/81#issuecomment-1384140747).

```
<div>
<p>This is a para with long space               in between and in the end      
   and a newline
</p>
    </div>

```
needs be formatted in buffer as

```
<div><p>This is a para with long space               in between and in the end      
   and a newline</p></div>  
```

But currently will be 

```
<div><p>This is a para with long space in between and in the end and a newline</p></div>  
```

Without this the relavant whitespace changes in Doxygen will not trigger builds.

We will need HTML whitespace compression, instead of string whitespace compression I feel. Maybe something like https://www.crummy.com/software/BeautifulSoup/bs4/doc/ supports it. We have to keep the performance under check if entire HTML DOMs gets created.

**Comment by twodrops** [comment]
@aniketsalve22 I thought I added a comment to your latest commit (https://github.com/boschglobal/doxysphinx/pull/89/commits/10f25a80efef10ccc8564962f5e0dc12ee68bf62), but do not see it anymore.

I feel this fix might eat some significant whitespace as well.
For example `and a newline` in
```
<div>
<p>This is a para with long space               in between and in the end      
   and a newline
</p>
    </div>
```

See more info on significant whitespace here in this article on XML (same applies to HTML)
https://www.oracle.com/technical-resources/articles/wang-whitespace.html

**Comment by twodrops** [comment]
As per the reply [here](https://github.com/doxygen/doxygen/issues/9838#issuecomment-1431212989) the issue is fixed.
We could perhaps test with the master branch of doxygen once to confirm.

**Comment by aniketsalve22** [comment]
Tried with doxygen 1.9.7 (49caa66a3b824d139cf83c4964c9a4bbe8c5c0e0) and the issue is solved.

**Pull request merged**
