### PR TITLE
fix(python-version): Updated python to 3.12 and dependencies

### PR DESCRIPTION
**Pull request by aniketsalve22**
Fixed package versions to make doxysphinx compatible with python 3.12

### CODE REVIEW

**Comment by winterz** [comment]
1. can this be merged so we can get doxysphinx for python3.12?  see #118

**Review by twodrops — APPROVED** [review]
The changes look good. Sorry for the delay.

**Comment by aniketsalve22** [comment]
> @aniketsalve22 Looks like we have an issue [here](https://github.com/boschglobal/doxysphinx/actions/runs/8819051755/job/24209326645#step:8:12). Perhaps due to the recent access right changes?

Yes. We will have to update the access rights for the token.

**Comment by winterz** [comment]
hmm, this is merged yet I'm not seeing a fix when trying to install with python3.12.  
is this because of the access rights problem?

**Comment by twodrops** [comment]
That's right. The python package creation did not go through. Sorry to keep you waiting.
@aniketsalve22 Can you please follow this up?

**Comment by twodrops** [comment]
@aniketsalve22 We are hit with this issue https://github.com/softprops/action-gh-release/issues/236
Tried the solutions there. It has to do with the recent migration to github enterprise, but not sure how it is affecting this. I have added as secret a token with all needed permissions 🙄

**Comment by twodrops** [comment]
@winterz @aniketsalve22
[doxysphinx 3.3.8](https://github.com/boschglobal/doxysphinx/releases/tag/v3.3.8) with python 3.12 support is out 🍾 🎆 🥳 
Thanks for your patience.

**Comment by twodrops** [comment]
@winterz @aniketsalve22 
And now finally done!!
https://pypi.org/project/doxysphinx/

**Comment by winterz** [comment]
yay it works here.  thanks so much

**Pull request merged**
